#!/usr/bin/env python

import click
from os.path import expanduser, isdir

# defaults
DEFAULT_PATH = expanduser("~")+"/.notes"

# create command group needed for subcomands
@click.group()
@click.option('--path', '-p', envvar='NOTES_PATH', default=DEFAULT_PATH, show_default=True)
@click.pass_context
def cli(ctx, path):
    ctx.obj["path"] = path



@cli.command('init')
@click.pass_context
def init(ctx):
    """Initialize notes directory"""

    # create local copies of ctx vaiables for easy access
    path = ctx.obj["path"]

    print("Creating notes archive at ", path)
    if(isdir(path)):
        print("Directory already exists. Stopping. Consider using -f/--force to force this action")


if __name__ == '__main__':
    cli(obj={})
