#!/usr/bin/env python

import click

from os import system
from os.path import expanduser, isdir

# defaults
DEFAULT_PATH = expanduser("~")+"/.notes"

# create command group needed for subcomands
@click.group(invoke_without_command=True)
@click.option('--force', '-f', default=False)
@click.option('--path', '-p', envvar='NOTES_PATH', default=DEFAULT_PATH, show_default=True)
@click.pass_context
def cli(ctx, path, force):
    ctx.obj["path"] = path
    ctx.obj["force"] = force

    if ctx.invoked_subcommand is None:
        system('tree ' + path)


@cli.command('init')
@click.pass_context
def init(ctx):
    """Initialize notes directory"""

    # create local copies of ctx vaiables for easy access
    path = ctx.obj["path"]
    force = ctx.obj["force"]

    if(isdir(path) and not force):
        print("Cannot create a notes directory at", path, "Path already exists")

    else:
        print("Creating notes archive at ", path)
        system("git init " + path)


@cli.command('create')
@click.pass_context
def create(ctx):
    pass



if __name__ == '__main__':
    cli(obj={})
